// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );                                               
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF9OqoWqezf9yj76gJVVrpvuwe8Lswdyo',
    appId: '1:7446842012:web:118399dae7490019c37b59',
    messagingSenderId: '7446842012',
    projectId: 'flutterfirebasefinal-9daa7',
    authDomain: 'flutterfirebasefinal-9daa7.firebaseapp.com',
    storageBucket: 'flutterfirebasefinal-9daa7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkw79uv81WAVIKcV7v1GEb8ZiWfclu1y8',
    appId: '1:7446842012:android:3eaadf30b0e3406dc37b59',
    messagingSenderId: '7446842012',
    projectId: 'flutterfirebasefinal-9daa7',
    storageBucket: 'flutterfirebasefinal-9daa7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Yqvvq2FA5FUbnWZhQvZGnGWZQqlrDrA',
    appId: '1:7446842012:ios:6d6566cbc008c401c37b59',
    messagingSenderId: '7446842012',
    projectId: 'flutterfirebasefinal-9daa7',
    storageBucket: 'flutterfirebasefinal-9daa7.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectClassup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Yqvvq2FA5FUbnWZhQvZGnGWZQqlrDrA',
    appId: '1:7446842012:ios:6d6566cbc008c401c37b59',
    messagingSenderId: '7446842012',
    projectId: 'flutterfirebasefinal-9daa7',
    storageBucket: 'flutterfirebasefinal-9daa7.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectClassup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF9OqoWqezf9yj76gJVVrpvuwe8Lswdyo',
    appId: '1:7446842012:web:3d8fd205a6fe1dd6c37b59',
    messagingSenderId: '7446842012',
    projectId: 'flutterfirebasefinal-9daa7',
    authDomain: 'flutterfirebasefinal-9daa7.firebaseapp.com',
    storageBucket: 'flutterfirebasefinal-9daa7.firebasestorage.app',
  );
}
